version: '3.1'

services:
  jtb:
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_ADMIN_NAMES=${BOT_ADMIN_NAMES}
      - BOT_ADMIN_CHAT_IDS=${BOT_ADMIN_CHAT_IDS}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    depends_on:
      - db
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_DB=jtb
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5431:5432
