version: '3.1'

services:
  jtb:
    build:
      context: .
    environment:
      - bot.username=${BOT_NAME}
      - bot.token=${BOT_TOKEN}
      - bot.admin_names=${BOT_ADMIN_NAMES}
      - bot.admin_chat_ids=${BOT_ADMIN_CHAT_IDS}
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}
    restart: always
    depends_on:
      - db
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_DB=jtb
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5431:5432
